# Generated by Django 6.0.5 on 2026-05-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customworkout_delete_workoutplan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customworkout',
            table='custom_workout',
        ),
    ]
