# Generated by Django 6.0.5 on 2026-05-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customworkout_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customworkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
    ]
