# Generated by Django 6.0.5 on 2026-05-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_users_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
