# Generated by Django 6.0.5 on 2026-05-12 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_loginuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(auto_now_add=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=20)),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'daily_meals',
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField()),
                ('total_calories', models.IntegerField(default=0)),
                ('total_protein', models.IntegerField(default=0)),
                ('target_calories', models.IntegerField()),
                ('target_protein', models.IntegerField()),
                ('goal_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'daily_summary',
            },
        ),
    ]
