# Generated by Django 6.0.5 on 2026-05-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_dailymeals_dailysummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeals',
            name='meal_type',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='MealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('total_calories', models.IntegerField()),
                ('total_protein', models.IntegerField()),
                ('target_calories', models.IntegerField()),
                ('target_protein', models.IntegerField()),
                ('goal_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'meal_history',
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(max_length=50)),
                ('daily_calories', models.IntegerField()),
                ('daily_protein', models.IntegerField()),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('activity_level', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'user_goal',
            },
        ),
        migrations.DeleteModel(
            name='DailySummary',
        ),
    ]
