# Generated by Django 6.0.5 on 2026-05-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('sessions_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('validity_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'booking_packages',
            },
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('price_per_session', models.IntegerField(default=500)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image_icon', models.CharField(default='👨\u200d🏫', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'trainers',
            },
        ),
        migrations.CreateModel(
            name='TrainerBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('session_type', models.CharField(blank=True, max_length=50, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('total_amount', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.CASCADE, to='user.trainers')),
            ],
            options={
                'db_table': 'trainer_bookings',
            },
        ),
        migrations.CreateModel(
            name='TrainerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='user.trainerbookings')),
            ],
            options={
                'db_table': 'trainer_reviews',
            },
        ),
    ]
